#####################################
# Image Setup
#####################################

ARG POSTGRES_VERSION=alpine
FROM postgres:${POSTGRES_VERSION}

LABEL maintainer="Bruno Aquino <bruno.gl.aquino@gmail.com>"

CMD ["postgres"]

EXPOSE 5432
